
default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
  username: ENV['POSTGRESAPP_USERNAME']
  password: ENV['POSTGRESAPP_PASSWORD']

development:
  <<: *default
  database: job-board_development

test:
  <<: *default
  database: job_board_test
